const deps = [
  'react',
  'react-dom',
  '@babel/core',
  '@babel/preset-env',
  'webpack-cli',
  'webpack',
  'web-vitals',
  'typescript',
  'style-loader',
  'react-scripts',
  'react-dom',
  'react',
  'jest',
  'babel-loader',
  'ajv',
  '@types/react-dom',
  '@types/react',
  '@types/node',
  '@types/jest',
  '@testing-library/user-event',
  '@testing-library/react',
  '@testing-library/jest-dom',
  '@babel/preset-react',
];

module.exports = { deps };
